### ISSUE TITLE
Best scope handler

### ISSUE THREAD

**Issue by carmas123** [angel-dart/angel_auth#49]
Hi all, please can you explain me what is the best way to handle user auth and manage her scope authorizations?

For example now I've this situation:

I create a plugin like this to handle login

```
Future<void> configureServer(Angel app) async {
  // Inizializzazione Authenticator
  var auth = AngelAuth<User>(jwtKey: app.configuration["jwt_secret"] as String, secureCookies: app.environment.isProduction);
  auth.serializer = (u) => u.id;
  auth.deserializer = (id) => _fetchUserById(id, app);
  await app.configure(auth.configureServer);

  auth.strategies['local'] = LocalAuthStrategy((username, password) async {
    var executor = app.container.make<QueryExecutor>();
    // Cerco l'Utente
    var query = UserQuery();
    query.where..username.equals(username);
    var user = await query.getOne(executor);
    if (user != null) {
      if (Password.verify(password, user.hashedPassword)) {
        return user;
      }
    }

    throw AngelHttpException.notAuthenticated();
  });

  // ROUTER - Login
  app.post('/auth/login', auth.authenticate('local'));
}

Future<User> _fetchUserById(id, Angel app) async {
  if (id is String) {
    var executor = app.container.make<QueryExecutor>();
    // Cerco l'Utente
    var query = UserQuery();
    query.where..id.equals(int.tryParse(id));
    var user = await query.getOne(executor);
    if (user != null) {
      return user;
    }
  }
  throw AngelHttpException.notAuthenticated();
}

```

Now what is the best way to manage the user authorization?

**Comment by thosakwe** [comment]
If you've called `await app.configure(auth.configureServer)`, then the `User` class will be injected into every request, as a factory/lazy singleton.

When you ask the container to make a `User` instance, it will check the `authorization` header for a JSON web token, validate its signature to make sure it wasn't forged, and then call `auth.deserializer` to return a `User` instance. 

All of the following will fetch a user:

```dart
app.get('/', (req, res) async {
  // `User` is an async injection, so you MUST call makeAsync
  var user = await req.container.makeAsync<User>();
});

// If you use dependency injection, the user will be resolved for you
app.get('/', ioc((User user) {
  return user.name;
}));

@Expose('/api/my')
class MyCtrl extends Controller {
   // `User` is injected here
   @Expose('/age')
   int getAge(User user) {
      var now = DateTime.now();
      return now.subtract(user.createdAt).inSeconds;
   }
}

```

There is also a middleware, `requireAuthentication<User>()`, that you can use that will automatically throw a `403 Forbidden` error for clients who are not logged in. As you can imagine, this can be very useful.

**Comment by thosakwe** [comment]
`angel_auth` is for authentication, not authorization (unfortunately both words start the same, so it's a bit confusing). Other than `requireAuthentication<User>()` (which is often all you need), any granular permissions, etc. are app-specific. Usually this isn't a problem, because logic will always vary from app to app.

**Comment by carmas123** [comment]
Yes this is true, but I intend to handle some request that need user to be logged in.
So for now if into @Expose method use myGet(User user) how can I check if the user is logged in?

**Comment by thosakwe** [comment]
That check will be performed automatically. Look at the implementation here: https://github.com/angel-dart/auth/blob/master/lib/src/plugin.dart#L106-L128

If there is no token present when `<User>` is requested, a 401 will be thrown.

**Comment by carmas123** [comment]
Oh very very good...!!
Regards
