### ISSUE TITLE
How to acquire authentication's information?

### ISSUE THREAD

**Issue by BLeAm** [angel-dart/angel_auth#50]
After authenticated how can I get the authentication's information in any routes?
Like,
```dart
app.post('/login',auth.authenticate('local'));
app.get('/user', (req, res){...});
```

how can I get authentication's information out of req?
According to the example, I don't quite get the concept of ioc function and it doesn't seem to work in action anyway.

**Comment by BLeAm** [comment]
I have looked into the implementation of requireAuthentication method and find the way to get the user object via 
```dart
req.container.makeAsync<User>();
```
so, this issue is supposed to be closed.

**Comment by thosakwe** [comment]
The way this plugin works as of version 2 is by inserting an async factory into the request container that returns a `User` (whatever type you gave it), *or* throws a `401` error if authentication fails.

For example, you can call `var user = await req.container.makeAsync<User>();`. However, in an `ioc` context, a `Controller`, or anything where reflection is being used, you can simply have `User` as a function/method parameter for your route, as you see in the example.

But what do you mean that `ioc` doesn’t work in action?

**Comment by BLeAm** [comment]
I was trying to use `ioc` without reflection and so that's why it didn't work, my fault.

BTW, thank you for your response. :)
